#!/usr/bin/env bash

# Follow however many symlinks are needed to get the true directory and name of this script
SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
    SOURCE=$(readlink "$SOURCE")
    [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPT_DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
SCRIPT_NAME="$( basename "$SOURCE" )"
PYVENV="${PYVENV:-$HOME/.pyvenv}"
VENV="$PYVENV/$SCRIPT_NAME"

#
# Do any setup needed
#
deactivate 2> /dev/null
source "$VENV/bin/activate"

#
# Update all
#
if [[ "$1" == "--update" ]]; then
    shift
    cp $SCRIPT_DIR/requirements_rocm.txt $SCRIPT_DIR/requirements.in
    fd -u requirements.txt $SCRIPT_DIR -x sed -e '$s/$/\n/' | sed '/^[[:space:]]*$/d' | awk '!seen[$0]++' | sort >> $SCRIPT_DIR/requirements.in
    uv pip compile $SCRIPT_DIR/requirements.in > $SCRIPT_DIR/requirements_all.txt;
    uv pip install --prerelease=allow --index-strategy=unsafe-best-match -r $SCRIPT_DIR/requirements_all.txt --extra-index-url=https://download.pytorch.org/whl/rocm6.0 --no-build-isolation
elif [[ "$1" == "--update-nightly" ]]; then
    shift
    cp $SCRIPT_DIR/requirements_rocm_nightly.txt $SCRIPT_DIR/requirements.in
    fd -u requirements.txt $SCRIPT_DIR -x sed -e '$s/$/\n/' | sed '/^[[:space:]]*$/d' | awk '!seen[$0]++' | sort >> $SCRIPT_DIR/requirements.in
    uv pip compile $SCRIPT_DIR/requirements.in > $SCRIPT_DIR/requirements_all.txt;
    uv pip install --prerelease=allow --index-strategy=unsafe-best-match -r $SCRIPT_DIR/requirements_all.txt --extra-index-url=https://download.pytorch.org/whl/nightly/rocm6.1 --no-build-isolation
fi

# Path to software entry point
SOFTWARE="$SCRIPT_DIR/main.py"

# Add any default args here
SOFTWARE_ARGS="--verbose --disable-auto-launch" 
if [[ "$1" == "--mode=0" || "$1" == "--mode=default" ]]; then
    shift
elif [[ "$1" == "--mode=1" || "$1" == "--mode=sdxl" ]]; then
    shift
    # Force fp16.
    SOFTWARE_ARGS="$SOFTWARE_ARGS --force-fp16"

    # Run the VAE in bf16, might lower quality.
    SOFTWARE_ARGS="$SOFTWARE_ARGS --bf16-vae"

    # Default preview method for sampler nodes.
    SOFTWARE_ARGS="$SOFTWARE_ARGS --preview-method none"

    # Use the split cross attention optimization. Ignored when xformers is used.
    SOFTWARE_ARGS="$SOFTWARE_ARGS --use-split-cross-attention"

    # Split the unet in parts to use less vram.
    #SOFTWARE_ARGS="$SOFTWARE_ARGS --lowvram"
    # When lowvram isn't enough.
    SOFTWARE_ARGS="$SOFTWARE_ARGS --novram"

    # Force ComfyUI to agressively offload to regular ram instead of keeping models in vram when it can.
    SOFTWARE_ARGS="$SOFTWARE_ARGS --disable-smart-memory"
fi
SOFTWARE_ARGS="$SOFTWARE_ARGS $@"

# Temporary environment variables
export HSA_OVERRIDE_GFX_VERSION=11.0.0
export HIP_VISIBLE_DEVICES=0
export ROCR_VISIBLE_DEVICES=0
export PYTORCH_ROCM_ARCH=gfx1102
export AMDGPU_TARGETS=gfx1102
export PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.8,max_split_size_mb:512

# Run software, passing all args from this script onwards
(cd $SCRIPT_DIR; python3 $SOFTWARE $SOFTWARE_ARGS)
