#!/usr/bin/env bash

# Follow however many symlinks are needed to get the true directory and name of this script
SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
    SOURCE=$(readlink "$SOURCE")
    [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPT_DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
SCRIPT_NAME="$( basename "$SOURCE" )"

function run() {
    PYVENV="${PYVENV:-$HOME/.pyvenv}"
    VENV="$PYVENV/$SCRIPT_NAME"
    REQ_IN="$SCRIPT_DIR/requirements.in"
    REQ_ALL="$SCRIPT_DIR/requirements_all.txt"
    ROCM_REQ="$SCRIPT_DIR/requirements_rocm.txt"

    #
    # Parse CLI Args
    #
    SOFTWARE_ARGS=""
    UPDATE=false
    QUICK=false
    for opt in "$@"; do
        case $opt in
            # ROCm Version
            "nightly")
                shift
                VENV="$VENV-nightly"
                ROCM_REQ="$SCRIPT_DIR/requirements_rocm_nightly.txt"
                ;;
            "lts")
                shift
                VENV="$VENV-lts"
                ROCM_REQ="$SCRIPT_DIR/requirements_rocm_lts.txt"
                ;;

            # Modes
            "update")
                shift
                UPDATE=true
                ;;

            "quick")
                shift
                QUICK=true
                ;;

            # CLI Presets
            "vanilla")
                shift
                SOFTWARE_ARGS=""
                ;;
        esac
    done
    EXTRA_INDEX_URL="$(head -n 1 $ROCM_REQ | awk -F '=' '{ print $2 }')"

    #
    # Activate venv
    #
    echo "Activating $VENV"
    deactivate 2> /dev/null
    source "$VENV/bin/activate"

    #
    # Update all
    #
    set -e
    if $UPDATE; then
        echo "Syncing $ROCM_REQ with --extra-index-url=$EXTRA_INDEX_URL"
        cp $ROCM_REQ $REQ_IN
        fd -e txt -u requirements.txt $SCRIPT_DIR -x sed -e '$s/$/\n/' | sed '/^[[:space:]]*$/d' | awk '!seen[$0]++' | sort >> $REQ_IN
        uv pip compile --prerelease=allow --index-strategy=unsafe-best-match --extra-index-url=$EXTRA_INDEX_URL --no-build-isolation $REQ_IN > $REQ_ALL
        uv pip install --prerelease=allow --index-strategy=unsafe-best-match --extra-index-url=$EXTRA_INDEX_URL --no-build-isolation -r $REQ_ALL 
    fi
    set +e

    #
    # Fast quit
    #
    if $QUICK; then
        SOFTWARE_ARGS="$SOFTWARE_ARGS --quick-test-for-ci"
    fi

    # Path to software entry point
    SOFTWARE="$SCRIPT_DIR/main.py"

    # Append any remaining CLI args
    SOFTWARE_ARGS="$SOFTWARE_ARGS $@"

    echo "Launching python3 $SOFTWARE $SOFTWARE_ARGS"
    (cd $SCRIPT_DIR; python3 $SOFTWARE $SOFTWARE_ARGS)
}

if [[ "$1" == "-h" || "$1" == "--help" || "$1" == "help" ]]; then
    (cd $SCRIPT_DIR; python3 main.py -h)
else
    # Change power profile
    CURRENT_PROFILE="$(power_profile status)"
    systemctl start performance.service
    run $@
    systemctl start "$CURRENT_PROFILE.service"
fi
